name: oauth_server
description: Servidor OAuth simples para Google Drive
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
