// Mocks generated by Mockito 5.4.6 from annotations
// in file_drive/test/providers/cloud_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i2;

import 'package:file_drive/src/providers/base/cloud_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderCapabilities_1 extends _i1.SmartFake
    implements _i3.ProviderCapabilities {
  _FakeProviderCapabilities_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CloudProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudProvider extends _i1.Mock implements _i3.CloudProvider {
  MockCloudProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get providerName =>
      (super.noSuchMethod(
            Invocation.getter(#providerName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#providerName),
            ),
          )
          as String);

  @override
  String get providerIcon =>
      (super.noSuchMethod(
            Invocation.getter(#providerIcon),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#providerIcon),
            ),
          )
          as String);

  @override
  _i2.Color get providerColor =>
      (super.noSuchMethod(
            Invocation.getter(#providerColor),
            returnValue: _FakeColor_0(this, Invocation.getter(#providerColor)),
          )
          as _i2.Color);

  @override
  _i3.ProviderStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.ProviderStatus.disconnected,
          )
          as _i3.ProviderStatus);

  @override
  _i5.Stream<_i3.ProviderStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i5.Stream<_i3.ProviderStatus>.empty(),
          )
          as _i5.Stream<_i3.ProviderStatus>);

  @override
  _i3.ProviderCapabilities get capabilities =>
      (super.noSuchMethod(
            Invocation.getter(#capabilities),
            returnValue: _FakeProviderCapabilities_1(
              this,
              Invocation.getter(#capabilities),
            ),
          )
          as _i3.ProviderCapabilities);

  @override
  _i5.Future<bool> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<bool> validateAuth() =>
      (super.noSuchMethod(
            Invocation.method(#validateAuth, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> refreshAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAuth, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
