name: file_cloud
description: "A Flutter widget for accessing files from cloud storage providers (Google Drive, Dropbox, OneDrive, etc.) with OAuth2 authentication."
version: 0.0.1
homepage: https://github.com/your-username/file_cloud

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Localization support  
  flutter_localizations:
    sdk: flutter
  
  # OAuth2 Authentication
  flutter_web_auth_2: ^4.0.1
  
  # HTTP requests for cloud provider APIs
  http: ^1.2.0
  
  # Local storage for account data
  shared_preferences: ^2.2.2
  
  # Internationalization
  intl: ^0.20.2
  
  # Path manipulation for file operations
  path: ^1.9.0
  
  # Platform detection
  universal_platform: ^1.1.0
  
  # SVG support for provider logos
  flutter_svg: ^2.0.10
  googleapis: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # For mocking in tests
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  # Enable generation of localization files
  generate: true
  
  # Assets for provider logos - INCLUDED IN PACKAGE
  assets:
    - assets/logos/google_drive.svg

# Internationalization configuration
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/l10n