// Mocks generated by Mockito 5.4.6 from annotations
// in file_drive/test/widgets/provider_content_needsreauth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i4;

import 'package:file_drive/src/models/cloud_folder.dart' as _i6;
import 'package:file_drive/src/models/cloud_item.dart' as _i10;
import 'package:file_drive/src/models/file_operations.dart' as _i11;
import 'package:file_drive/src/models/oauth_types.dart' as _i5;
import 'package:file_drive/src/models/search_models.dart' as _i13;
import 'package:file_drive/src/providers/base/cloud_provider.dart' as _i3;
import 'package:file_drive/src/providers/base/oauth_cloud_provider.dart' as _i7;
import 'package:file_drive/src/storage/token_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenStorage_0 extends _i1.SmartFake implements _i2.TokenStorage {
  _FakeTokenStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderCapabilities_1 extends _i1.SmartFake
    implements _i3.ProviderCapabilities {
  _FakeProviderCapabilities_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_2 extends _i1.SmartFake implements _i4.Color {
  _FakeColor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthParams_3 extends _i1.SmartFake implements _i5.OAuthParams {
  _FakeOAuthParams_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCloudFolder_4 extends _i1.SmartFake implements _i6.CloudFolder {
  _FakeCloudFolder_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OAuthCloudProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuthCloudProvider extends _i1.Mock
    implements _i7.OAuthCloudProvider {
  MockOAuthCloudProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic Function(_i5.OAuthParams) get urlGenerator =>
      (super.noSuchMethod(
            Invocation.getter(#urlGenerator),
            returnValue: (_i5.OAuthParams __p0) => null,
          )
          as dynamic Function(_i5.OAuthParams));

  @override
  _i2.TokenStorage get tokenStorage =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStorage),
            returnValue: _FakeTokenStorage_0(
              this,
              Invocation.getter(#tokenStorage),
            ),
          )
          as _i2.TokenStorage);

  @override
  String get providerId =>
      (super.noSuchMethod(
            Invocation.getter(#providerId),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#providerId),
            ),
          )
          as String);

  @override
  _i3.ProviderCapabilities get capabilities =>
      (super.noSuchMethod(
            Invocation.getter(#capabilities),
            returnValue: _FakeProviderCapabilities_1(
              this,
              Invocation.getter(#capabilities),
            ),
          )
          as _i3.ProviderCapabilities);

  @override
  bool get needsReauth =>
      (super.noSuchMethod(Invocation.getter(#needsReauth), returnValue: false)
          as bool);

  @override
  bool get isTokenExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isTokenExpired),
            returnValue: false,
          )
          as bool);

  @override
  _i3.ProviderStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.ProviderStatus.disconnected,
          )
          as _i3.ProviderStatus);

  @override
  _i9.Stream<_i3.ProviderStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i9.Stream<_i3.ProviderStatus>.empty(),
          )
          as _i9.Stream<_i3.ProviderStatus>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get providerName =>
      (super.noSuchMethod(
            Invocation.getter(#providerName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#providerName),
            ),
          )
          as String);

  @override
  String get providerIcon =>
      (super.noSuchMethod(
            Invocation.getter(#providerIcon),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#providerIcon),
            ),
          )
          as String);

  @override
  _i4.Color get providerColor =>
      (super.noSuchMethod(
            Invocation.getter(#providerColor),
            returnValue: _FakeColor_2(this, Invocation.getter(#providerColor)),
          )
          as _i4.Color);

  @override
  _i9.Future<Map<String, dynamic>?> getCurrentUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserInfo, []),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<Map<String, Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i9.Future<Map<String, Map<String, dynamic>>>.value(
              <String, Map<String, dynamic>>{},
            ),
          )
          as _i9.Future<Map<String, Map<String, dynamic>>>);

  @override
  _i9.Future<bool> switchToUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#switchToUser, [userId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initializeFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#initializeFromStorage, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<Map<String, dynamic>?> fetchUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserInfo, []),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<bool> refreshAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i5.OAuthParams createOAuthParams() =>
      (super.noSuchMethod(
            Invocation.method(#createOAuthParams, []),
            returnValue: _FakeOAuthParams_3(
              this,
              Invocation.method(#createOAuthParams, []),
            ),
          )
          as _i5.OAuthParams);

  @override
  _i9.Future<Map<String, dynamic>?> getUserInfoFromProvider(
    String? accessToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfoFromProvider, [accessToken]),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<bool> validateTokenWithProvider(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#validateTokenWithProvider, [accessToken]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i5.AuthResult?> refreshTokenWithProvider(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokenWithProvider, [refreshToken]),
            returnValue: _i9.Future<_i5.AuthResult?>.value(),
          )
          as _i9.Future<_i5.AuthResult?>);

  @override
  _i9.Future<void> revokeToken(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#revokeToken, [accessToken]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void updateStatus(_i3.ProviderStatus? newStatus) => super.noSuchMethod(
    Invocation.method(#updateStatus, [newStatus]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<Map<String, dynamic>?> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<bool> validateAuth() =>
      (super.noSuchMethod(
            Invocation.method(#validateAuth, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> refreshAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAuth, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<bool> performAuthValidation() =>
      (super.noSuchMethod(
            Invocation.method(#performAuthValidation, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> performAuthRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#performAuthRefresh, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<List<_i10.CloudItem>> listItems(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#listItems, [folderId]),
            returnValue: _i9.Future<List<_i10.CloudItem>>.value(
              <_i10.CloudItem>[],
            ),
          )
          as _i9.Future<List<_i10.CloudItem>>);

  @override
  _i9.Future<_i6.CloudFolder> createFolder(String? name, String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#createFolder, [name, parentId]),
            returnValue: _i9.Future<_i6.CloudFolder>.value(
              _FakeCloudFolder_4(
                this,
                Invocation.method(#createFolder, [name, parentId]),
              ),
            ),
          )
          as _i9.Future<_i6.CloudFolder>);

  @override
  _i9.Stream<_i11.UploadProgress> uploadFile(_i11.FileUpload? fileUpload) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [fileUpload]),
            returnValue: _i9.Stream<_i11.UploadProgress>.empty(),
          )
          as _i9.Stream<_i11.UploadProgress>);

  @override
  _i9.Future<_i12.Uint8List> downloadFile(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [fileId]),
            returnValue: _i9.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i9.Future<_i12.Uint8List>);

  @override
  _i9.Future<void> deleteItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [itemId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> moveItem(String? itemId, String? newParentId) =>
      (super.noSuchMethod(
            Invocation.method(#moveItem, [itemId, newParentId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> renameItem(String? itemId, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#renameItem, [itemId, newName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i10.CloudItem>> searchItems(_i13.SearchQuery? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [query]),
            returnValue: _i9.Future<List<_i10.CloudItem>>.value(
              <_i10.CloudItem>[],
            ),
          )
          as _i9.Future<List<_i10.CloudItem>>);

  @override
  _i9.Future<_i10.CloudItem?> getItemById(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [itemId]),
            returnValue: _i9.Future<_i10.CloudItem?>.value(),
          )
          as _i9.Future<_i10.CloudItem?>);

  @override
  _i9.Future<List<_i6.CloudFolder>> getFolderPath(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getFolderPath, [folderId]),
            returnValue: _i9.Future<List<_i6.CloudFolder>>.value(
              <_i6.CloudFolder>[],
            ),
          )
          as _i9.Future<List<_i6.CloudFolder>>);
}
