name: file_cloud_example_server
description: Example OAuth server for File Cloud widget development and testing
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.2.0

  path: any
dev_dependencies:
  lints: ^5.0.0